#!/data/data/com.termux/files/usr/bin/bash
# =============================================================================
#  deb2pkg.sh  —  Convert a .deb package to .pkg.tar.xz for Termux pacman
# =============================================================================
#  Usage:  ./deb2pkg.sh <package.deb>
#
#  Output: <package>.pkg.tar.xz  (ready for `pacman -U`)
#
#  Requires: dpkg (install via: pacman -S dpkg)
#
#  How it works:
#    1. Extracts the .deb with dpkg-deb
#    2. Reads control metadata (Package, Version, Architecture, etc.)
#    3. Generates .PKGINFO (pacman metadata)
#    4. Repacks everything as .pkg.tar.xz
#
#  This only works for pre-built binary .deb packages. It does NOT
#  build from source — that's what proper PKGBUILD + makepkg are for.
# =============================================================================

set -e

# --- Config ----------------------------------------------------------
COMPRESSION="xz"      # xz or zst
SCRIPT_NAME=$(basename "$0")

# --- Help -------------------------------------------------------------
if [ $# -eq 0 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo "Usage: $SCRIPT_NAME <package.deb>"
    echo ""
    echo "Converts a .deb package to .pkg.tar.xz for Termux pacman."
    echo "Output: <package>.pkg.tar.xz"
    echo ""
    echo "Examples:"
    echo "  $SCRIPT_NAME virglrenderer_1.1.1-latest_aarch64.deb"
    echo "  $SCRIPT_NAME angle-android_2.1.2-latest.deb"
    echo "  $SCRIPT_NAME mesa-vulkan-icd-wrapper_25.0.0-1_aarch64.deb"
    exit 0
fi

DEB_FILE="$1"

if [ ! -f "$DEB_FILE" ]; then
    echo "ERROR: File not found: $DEB_FILE" >&2
    exit 1
fi

# --- Detect decompressor ----------------------------------------------
if command -v dpkg-deb >/dev/null 2>&1; then
    DEB_EXTRACT="dpkg-deb -R"
elif command -v ar >/dev/null 2>&1 && command -v tar >/dev/null 2>&1; then
    DEB_EXTRACT="ar p"  # fallback: extract data.tar.xz manually
else
    echo "ERROR: Need dpkg-deb (install: pacman -S dpkg)" >&2
    exit 1
fi

WORKDIR=$(mktemp -d)
trap "rm -rf '$WORKDIR'" EXIT

echo "==> Extracting: $DEB_FILE"

# Extract the .deb
if command -v dpkg-deb >/dev/null 2>&1; then
    dpkg-deb -R "$DEB_FILE" "$WORKDIR/extracted"
    CTRL_DIR="$WORKDIR/extracted/DEBIAN"
    DATA_DIR="$WORKDIR/extracted"
else
    # Manual extraction via ar + tar
    mkdir -p "$WORKDIR/extracted"
    cd "$WORKDIR/extracted"
    ar p "$DEB_FILE" control.tar.gz | tar -xz 2>/dev/null || \
    ar p "$DEB_FILE" control.tar.xz | tar -xJ 2>/dev/null
    CTRL_DIR="$WORKDIR/extracted"
    
    mkdir -p "$WORKDIR/data"
    cd "$WORKDIR/data"
    ar p "$DEB_FILE" data.tar.gz | tar -xz 2>/dev/null || \
    ar p "$DEB_FILE" data.tar.xz | tar -xJ 2>/dev/null
    DATA_DIR="$WORKDIR/data"
fi

# --- Read control metadata -------------------------------------------
CTRL_FILE="$CTRL_DIR/control"
if [ ! -f "$CTRL_FILE" ]; then
    echo "ERROR: No control file found in .deb" >&2
    exit 1
fi

# Extract fields from control (simple parser)
pkgname=$(grep -E "^Package:" "$CTRL_FILE" | sed 's/^Package: *//')
pkgver=$(grep -E "^Version:" "$CTRL_FILE" | sed 's/^Version: *//' | sed 's/[: ].*//')
pkgdesc=$(grep -E "^Description:" "$CTRL_FILE" | sed 's/^Description: *//')
arch=$(grep -E "^Architecture:" "$CTRL_FILE" | sed 's/^Architecture: *//')
maintainer=$(grep -E "^Maintainer:" "$CTRL_FILE" | sed 's/^Maintainer: *//')
license=$(grep -E "^License:" "$CTRL_FILE" | sed 's/^License: *//')
url=$(grep -E "^Homepage:" "$CTRL_FILE" | sed 's/^Homepage: *//')
depends=$(grep -E "^Depends:" "$CTRL_FILE" | sed 's/^Depends: *//')

# Defaults for missing fields
[ -z "$pkgname" ] && pkgname=$(basename "$DEB_FILE" .deb)
[ -z "$pkgver" ] && pkgver="1.0-1"
[ -z "$arch" ] && arch="aarch64"
[ -z "$license" ] && license="custom"
[ -z "$url" ] && url="https://github.com/ar37-rs/virgl-angle"

# Sanitize version for pacman (remove epoch colons, etc.)
pkgver=$(echo "$pkgver" | sed 's/^[0-9]*://')  # strip epoch

echo "  Package : $pkgname"
echo "  Version : $pkgver"
echo "  Arch    : $arch"

# --- Calculate total installed size -----------------------------------
PKG_SIZE=$(du -sk "$DATA_DIR" 2>/dev/null | tail -1 | awk '{print $1 * 1024}')
[ -z "$PKG_SIZE" ] && PKG_SIZE=0

# --- Generate .PKGINFO ------------------------------------------------
PKGINFO="$WORKDIR/.PKGINFO"
{
    echo "# Generated by deb2pkg.sh"
    echo "# From: $DEB_FILE"
    echo ""
    echo "pkgname = $pkgname"
    echo "pkgver = $pkgver"
    echo "pkgdesc = $pkgdesc"
    echo "url = $url"
    echo "builddate = $(date -u +%s)"
    echo "packager = $maintainer"
    echo "size = $PKG_SIZE"
    echo "arch = $arch"
    echo "license = $license"

    # Convert apt depends to pacman depends
    if [ -n "$depends" ]; then
        IFS=',' read -ra DEPS <<< "$depends"
        for dep in "${DEPS[@]}"; do
            dep=$(echo "$dep" | sed 's/ *([^)]*)//g; s/ *$//; s/^ *//')
            [ -n "$dep" ] && echo "depend = $dep"
        done
    fi

    # Add our known virtual provides for the GPU stack
    case "$pkgname" in
        mesa-vulkan-icd-wrapper)
            echo "depend = vulkan-loader-generic"
            ;;
    esac
} > "$PKGINFO"

# --- Build the .pkg.tar.xz -------------------------------------------
cd "$DATA_DIR"
OUTPUT_DIR=$(dirname "$(realpath "$DEB_FILE")")
OUTPUT_FILE="$OUTPUT_DIR/${pkgname}-${pkgver}-${arch}.pkg.tar.xz"

echo "==> Building: $(basename "$OUTPUT_FILE")"

# Create the package archive: files first, then .PKGINFO at the root
tar -cJf "$OUTPUT_FILE" \
    --owner=0 --group=0 \
    --transform="s|^\./||" \
    --transform="s|^$WORKDIR/\.PKGINFO|.PKGINFO|" \
    . "$PKGINFO" 2>/dev/null || \
tar -cJf "$OUTPUT_FILE" \
    --owner=0 --group=0 \
    . 2>/dev/null

# If the above failed, try simpler approach
if [ ! -f "$OUTPUT_FILE" ] || [ ! -s "$OUTPUT_FILE" ]; then
    cd "$DATA_DIR"
    # Pack files first
    tar -cJf "$OUTPUT_FILE" --owner=0 --group=0 .
    # Create a temp dir with .PKGINFO added
    TMPPKG=$(mktemp -d)
    cp "$PKGINFO" "$TMPPKG/.PKGINFO"
    cp -r "$DATA_DIR"/* "$TMPPKG/" 2>/dev/null || true
    cd "$TMPPKG"
    tar -cJf "$OUTPUT_FILE" --owner=0 --group=0 .
    rm -rf "$TMPPKG"
fi

echo ""
echo "✅ Done: $(basename "$OUTPUT_FILE")"
echo "   Install with: pacman -U $(basename "$OUTPUT_FILE")"

# Output the filename for scripting
echo "$OUTPUT_FILE"
